version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: smartcart-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartcart
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: smartcart-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
